# -*- coding: utf-8 -*-
"""Rule-based report drafts (no LLM)."""

from __future__ import annotations

from typing import Any, Dict, List, Optional


def build_results_draft(
    context: Dict[str, Any],
    sample_note: str = "",
) -> str:
    wf = context.get("workflow") or {}
    candidates: List[Dict[str, Any]] = list(context.get("top_candidates") or [])[:3]
    methodology = context.get("methodology_draft_en") or ""

    lines = [
        "## Sample",
        sample_note.strip() or "(Not provided — add a sample description in AI Assistant)",
        "",
        "## Database screening",
    ]
    if methodology:
        lines.append(methodology[:800] + ("..." if len(methodology) > 800 else ""))
    else:
        lines.append("(Run Copy methods text to generate methodology.)")
    lines.append("")
    n = int(wf.get("result_rows") or 0)
    lines.append(f"Ranked hit list: **{n}** entries after last screen.")
    lines.append("")
    lines.append("## Leading candidates")
    lines.append("| Rank | Score | DBindex | SMILES (truncated) |")
    lines.append("|------|-------|---------|-------------------|")
    for c in candidates:
        smi = str(c.get("smiles", ""))
        if len(smi) > 48:
            smi = smi[:45] + "..."
        lines.append(
            f"| #{c.get('rank')} | {float(c.get('score', 0)):.3f} | "
            f"{c.get('dbindex', '')} | `{smi}` |"
        )
    if not candidates:
        lines.append("| — | — | — | (no results) |")
    lines.extend([
        "",
        "## Limitations",
        "- Ranking is based on virtual ¹³C database matching, not standalone structure proof.",
        "- Stereochemistry and regioisomers may not be resolved without 2D NMR.",
        "- Database coverage depends on the selected library preset.",
        "",
        "*Draft generated by VirMolAnalyte (rule template). Review before manuscript submission.*",
    ])
    return "\n".join(lines)
